Rails.application.routes.draw do
get '/profiles/id' => 'application#show'
get '/profile/menu' => 'application#menu' 
get '/profile/steve' => 'application#third'
get '/profile/sonic' => 'application#first'
get '/profile/mario' => 'application#second'
get '/profile/lucario' => 'application#fourth'
get '/profile/archivist' => 'application#fifth'
get '/profile/ike' => 'application#sixth'
get '/profile/spyro' => 'application#seventh'
get '/profile/dk' => 'application#eighth'
get '/profile/luigi' => 'application#ninth'
get '/profile/barbarian' => 'application#tenth'
get '/gifs/:id/destroy' => 'application#destroy'
end
